### ISSUE TITLE
FPS instrument: fps.csv and frames.csv files are empty

### ISSUE THREAD

**Issue by Leo-Yan** [ARM-software/workload-automation#941] opened 2019-01-09 02:51 UTC
Hi there,

When I use fps instrument with jankbench, and found below issues:

- The first issue is if use fps instrument with property "force_surfaceflinger: true", then I can see fps.csv and frames.csv are empty; and in the results.csv file all fps related statistics are zeros.

You could refer the enclosed file [jankbench.yaml](https://github.com/ARM-software/workload-automation/files/2739181/jankbench.yaml.txt) and [jankbench.zip](https://github.com/ARM-software/workload-automation/files/2739180/jankbench.zip) for agenda and output results.

- The second issue is if use fps instrument with property "force_surfaceflinger: false", then fps.csv is still empty and frames.csv contains frames information.  So results.csv can generate fps related statistics.

So in this case, should we expect fps.csv will contain logs for dumpsys command?

You could refer the enclosed file [jankbench_nosf.yaml](https://github.com/ARM-software/workload-automation/files/2739179/jankbench_nosf.yaml.txt) and [jankbench_nosf.zip](https://github.com/ARM-software/workload-automation/files/2739178/jankbench_nosf.zip) for agenda and output results.

Thanks,
Leo Yan

**Comment by marcbonnici** [comment] 2019-01-09 13:58
Hello,

Thanks for reporting your findings. When using gfxinfo (`force_surfaceflinger=False`) the empty fps.csv was caused by discrepancy in the time units being used causing an incorrect value to be used when determining whether the value was below the drop threshold. I have submitted a PR to fix this in devlib: https://github.com/ARM-software/devlib/pull/359 so would you be able to pull the latest version of devlib and see if this resolves your issue? 

When using surface flinger to collect data the `view` that is used to obtain the statistic of the running app can be device specific and may need customizing which appears to be the case looking at your provided logs. For example for the `list_view` test as part of Jankbench you specified, the necessary view was:  `com.android.benchmark/com.android.benchmark.ui.ListViewScrollActivity#0`.

If you're are using a device running Android M or above then using gfxinfo is the preferred method of data collection as this tends to be more reliable and does not require the adjustment of the workload `view`. 

Regards,
Marc

**Comment by Leo-Yan** [comment] 2019-01-09 15:08
Hi @marcbonnici ,

I tried to use git pull latest devlib and use command "sudo python setup.py install", but I can see WA still use some old version devlib rather than the latest devlib.

I also tried to export PYTHONPATH like "export PYTHONPATH=~/Work2/Develop/tools/devlib:$PYTHONPATH", but still cannot let WA to use the devlib in specified path.

Could you tell me how to use the latest devlib?

**Comment by marcbonnici** [comment] 2019-01-09 16:24
In theory pulling the latest version and installing like that should work, however a couple of things:
  - Could you check that you are using the same version of Python when installing devlib and when running 
    WA if you have multiple versions on the machine? 
- Could you try completely removing the current version of devlib before attempting to reinstall to ensure that it is not installing in a different location and causing the old version to be picked up. If you have pip installed try `sudo pip uninstall devlib`

**Comment by Leo-Yan** [comment] 2019-01-10 10:43
On Wed, Jan 09, 2019 at 01:58:34PM +0000, Marc Bonnici wrote:

[...]

> When using surface flinger to collect data the `view` that is used to obtain the statistic of the running app can be device specific and may need customizing which appears to be the case looking at your provided logs. For example for the `list_view` test as part of Jankbench you specified, the necessary view was:  `com.android.benchmark/com.android.benchmark.ui.ListViewScrollActivity#0`.

Jankbench is quite special due we need to specify different views.

I tried Exoplayer with Surface Flinger for collecting frame data, it
still failed to capture frame related info.

So in the file wa/instruments/fps.py, I can see for ExoPlayer in below
sentence the getattr() [1] will return back value is:
  SurfaceView - com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.PlayerActivity

But if use the command 'dumpsys SurfaceFlinger --list' it returns back
the view as:
  SurfaceView - com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.PlayerActivity#0

Below is my change so that Surface Flinger mode can work well for
video frame rate statistics, please check if this is feasible for you?

~~~
diff --git a/devlib/utils/rendering.py b/devlib/utils/rendering.py
index 29c4bea..e20ff59 100644
--- a/devlib/utils/rendering.py
+++ b/devlib/utils/rendering.py
@@ -132,7 +132,7 @@ class SurfaceFlingerFrameCollector(FrameCollector):

     def collect_frames(self, wfh):
         for activity in self.list():
-            if activity == self.view:
+            if self.view in activity:
                 wfh.write(self.get_latencies(activity).encode('utf-8'))

     def clear(self):
~~~

[1] https://github.com/ARM-software/workload-automation/blob/master/wa/instruments/fps.py#L113

**Comment by marcbonnici** [comment] 2019-01-10 13:04
> I found WA has had requirement for devlib versions, so I need workaround this requirement by changing setup.py as below and reinstall WA; after this I can see fps.csv can work well with latest devlib.

Ah ok sorry yes if you were running the release version of WA it will have the release dependency for devlib which apparently causes it to ignore development versions install on the system.


> This means there have an extra suffix "#0' is added into the surfaceFlinger lists.  To correct
this issue below is my change so that Surface Flinger mode can work well for
video frame rate statistics, please check if this is feasible for you?

In theory this might work however I am slightly wary of allowing for matching so easily as this could interfere with duplicate matches on some devices. For example running this on a hikey960 these are the some of the views that are listed related to exoplayer, 2 of which would match if we allowed for the loose matching and I am unsure how this may affect the results or how other devices may behave?
```
24b4430 com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.PlayerActivity#0
Background for -SurfaceView - com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.PlayerActivity#0
SurfaceView - com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.PlayerActivity#0
com.google.android.exoplayer2.demo/com.google.android.exoplayer2.demo.PlayerActivity#0
```

**Comment by Leo-Yan** [comment] 2019-01-10 14:10
If so, can we permit the user to specify view name from agenda yaml file?  Finally, we give the user a chance to set the view who is interested in.

**Comment by marcbonnici** [comment] 2019-01-10 15:11
Yes I think that should be the safest way to go and have submitted a PR to add this: https://github.com/ARM-software/workload-automation/pull/946

**Comment by marcbonnici** [comment] 2019-01-11 10:14
This has now been merged in the latest version of WA.

**Closed** 2019-01-21 10:03 UTC
